title: Xplore Developer Documentation
description: A brief description of what things have been done and how, for future reference.
theme: just-the-docs

url: https://xplorethejourney.github.io
search_enabled: true
